config/routes.rb
PiensaEnTic::Application.routes.draw do
  resources :entradas

  get '/submit' =>'entradas#new'

  root 'home#index'

  

end

app/models/entrada.rb
class Entrada < ActiveRecord::Base
	validates :nombre, presence: true, format:{ with: /\A([a-zA-Z]| )+\z/, message: "Solo se admiten letras" }
	validates :email, presence: true, format:{ with: /\A[a-zA-Z0-9]+@[a-zA-Z0-9]+(.[a-zA-Z]+)+\z/, message: "No es un email valido" }
	validates :colegio, presence: true, format:{ with: /\A([a-zA-Z]| )+\z/, message: "Solo se admiten letras" }
	validates :nivel, presence: true
	validates :ciudad, presence: true, format:{ with: /\A([a-zA-Z]| )+\z/, message: "Solo se admiten letras" }
	validates :link_video, presence: true, format:{ with: /\A(http:\/\/|https:\/\/)(\w|\W)+\z/, message: "No es una URL Valida" }
	validates :link_bloopers, :allow_blank => true, format:{ with: /\A(http:\/\/|https:\/\/)(\w|\W)+\z/, message: "No es una URL Valida" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: [:show, :edit, :update, :destroy]

  # GET /entradas
  # GET /entradas.json
  def index
    @entradas = Entrada.all
  end

  # GET /entradas/1
  # GET /entradas/1.json
  def show
  end

  # GET /entradas/new
  def new
    @entrada = Entrada.new
  end

  # GET /entradas/1/edit
  def edit
  end

  # POST /entradas
  # POST /entradas.json
  def create
    @entrada = Entrada.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to :controller => 'home', :action =>'index', :notice => 'La entrada fue creada de manera exitosa.' }
        #format.json { render action: 'show', status: :created, location: @entrada }
      else
        format.html { redirect_to :controller => 'home', :action =>'index', notice: 'La entrada no fue creada.' }
        #format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entradas/1
  # PATCH/PUT /entradas/1.json
  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to @entrada, notice: 'Entrada was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entradas/1
  # DELETE /entradas/1.json
  def destroy
    @entrada.destroy
    respond_to do |format|
      format.html { redirect_to entradas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entrada_params
      params.require(:entrada).permit(:nombre, :email, :colegio, :nivel, :ciudad, :link_video, :link_bloopers)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@entrada = Entrada.new
		@entradas = Entrada.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entradas/_form.html.erb
<%= form_for(@entrada) do |f| %>
  <% if @entrada.errors.any? %>
    <div id="error_explanation">
      <p class="copy-02"><%= pluralize(@entrada.errors.count, "error") %> prohibited this entrada from being saved:</p>

      <ul>
      <% @entrada.errors.full_messages.each do |msg| %>
        <p class="copy-02"><li><%= msg %></li></p>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class ="signup-form">

    <p class="copy-02"><%= f.label :nombre %></p>
    <%= f.text_field :nombre %>

    <p class="copy-02"><%= f.label :email %></p>
    <%= f.text_field :email %>

    <p class="copy-02"><%= f.label :colegio %></p>
    <%= f.text_field :colegio %>

   <p class="copy-02"> <%= f.label :nivel, 'Grado' %></p>
    <%= f.text_field :nivel %>

    <p class="copy-02"><%= f.label :ciudad %></p>
    <%= f.text_field :ciudad %>

    <p class="copy-02"><%= f.label :link_video, 'Link del video' %></p>
    <%= f.text_field :link_video %>

    <p class="copy-02"><%= f.label :link_bloopers, 'Link de los bloopers (opcional)' %></p>
    <%= f.text_field :link_bloopers %>
<p class="copy-02"><BR></p>
    <%= f.submit "Enviar",:class =>"button main rounded" %>
</div>
<% end %>

app/views/entradas/edit.html.erb
<h1>Editing entrada</h1>

<%= render 'form' %>

<%= link_to 'Show', @entrada %> |
<%= link_to 'Back', entradas_path %>

app/views/entradas/index.html.erb
<h1>Listing entradas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Colegio</th>
      <th>Ciudad</th>
      <th>Link video</th>
      <th>Link bloopers</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entradas.each do |entrada| %>
      <tr>
        <td><%= entrada.nombre %></td>
        <td><%= entrada.colegio %></td>
        <td><%= entrada.ciudad %></td>
        <% if entrada.link_video.include? "http://" or entrada.link_video.include? "https://" %>
        <td><a href=<%= entrada.link_video %>>LINK</a></td>
        <% else %>
        <td>NO DISPONIBLE</td>
        <% end %>
        <% if entrada.link_bloopers.include? "http://" or entrada.link_bloopers.include? "https://" %>
        <td><a href=<%= entrada.link_bloopers %>>LINK</a></td>
        <% else %>
        <td>NO DISPONIBLE</td>
        <% end %>
        <td><%= link_to 'Show', entrada %></td>
        <td><%= link_to 'Edit', edit_entrada_path(entrada) %></td>
        <td><%= link_to 'Destroy', entrada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Entrada', new_entrada_path %> -->

app/views/entradas/new.html.erb
<h1>New entrada</h1>

<%= render 'form' %>

<%= link_to 'Back', entradas_path %>

app/views/entradas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @entrada.nombre %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entrada.email %>
</p>

<p>
  <strong>Colegio:</strong>
  <%= @entrada.colegio %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @entrada.nivel %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @entrada.ciudad %>
</p>

<p>
  <strong>Link video:</strong>
  <%= @entrada.link_video %>
</p>

<p>
  <strong>Link bloopers:</strong>
  <%= @entrada.link_bloopers %>
</p>

<%= link_to 'Edit', edit_entrada_path(@entrada) %> |
<%= link_to 'Back', entradas_path %>

app/views/home/index.html.erb
<!DOCTYPE HTML>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
    <title>PiensaEnTic</title>
    <meta name="description" content="Lithium Description" />
    <%= stylesheet_link_tag "plugins", media: "screen" %>
    <%= javascript_include_tag "libs/modernizr-2.6.2.min.js" %>

  </head>

<body>
  
  <section id="page-container">


     <!-- HERO -->
    <section id="page-hero">
      <div class="site-inner">
        <header>
          <div class="brand-logo">
            <%= image_tag "sintitulo.png", :style => "height:400px" %></figure>
          </div>
        </header>
        
      </div>
    </section>


    <!-- ABOUT -->
    <section id="page-about" class="section">
      <div class="site-inner">
        <p class="copy-01">
          Es una convocatoria dirigida a chicos y chicas de 10o  y 11o  grado en colegios de Colombia, con 15 años de edad o más a la fecha de cierre de la convocatoria, para que nos digan en un video de máximo 1 minuto, de una manera creativa y clara, por qué es importante estudiar ingeniería de sistemas.</p>
        <p class="copy-01">
          <h1 class="heading h-01">¿Qué puedo hacer en el video?</h1>
        <p class="copy-01">Lo que quieras. El formato es completamente libre; puede tener un testimonio, entrevistas, video musical, poesía, receta de cocina, coreografía... lo que consideres importante sobre la carrera, las posibilidades de crecimiento, el estado del sector y todas las cosas buenas que se pueden decir sobre por qué estudiar ingeniería de sistemas.</p>


        <h1 class="heading h-01">¿Cómo se participa?</h1>

        <div class="columns">
          <aside>
            <h3 class="heading h-03">1. CREA</h3>
            <p class="copy-02">Piensa en la importancia de estudiar ingeniería de sistemas, crea un video y súbelo a YouTube. Si no tienes cuenta, crea una.</p>
          </aside>

          <aside>
            <h3 class="heading h-03">2. REGISTRATE</h3>
            <p class="copy-02">Entra en la página www.piensaentic.com y regístrate ingresando la información de contacto requerida y el enlace a tu video.</p>
          </aside>

          <aside>
            <h3 class="heading h-03">3. COMPARTE</h3>
            <p class="copy-02">Tus amigos podrán votar por tu video directamente en YouTube, tienen hasta las 11:59pm del 30 de Septiembre para votar.</p>
          </aside>
          
        </div>
        <br>
        <div class="columns">
          
          <aside>
            <h3 class="heading h-03">4. VOTA</h3>
            <p class="copy-02">Los 10 videos de chicos y los 10 videos de chicas que tengan más “likes” o “Me gusta” en YouTube seran pre-seleccionados.</p>
          </aside>
          <aside>
            <h3 class="heading h-03">5. SELECCION</h3>
            <p class="copy-02">Los videos pre-seleccionados seran evaluados por un jurado calificador y escogeran un video de chicos y uno de chicas.</p>
          </aside>
          <aside>
            <h3 class="heading h-03">6. GANA</h3>
            <p class="copy-02">El video ganador será anunciado en la Feria POP de la Universidad del Norte el viernes 3 de octubre, a las 4:30pm.</p>
          </aside>
        </div>
      </div>
    </section>


    <!-- HERO -->
    <section id="page-work" class="section">

      <div class="my-work-container">
        <div class="site-inner">
          <h1 class="heading h-01">VIDEOS</h1>
        </div>

        <section id="work-grid" class="site-inner">
          <% @entradas.each do |entrada| %>
          <% if entrada.link_video.match(/(http:\/\/|https:\/\/|)(www.youtube.com\/watch\?v=|youtu.be\/)/)%>
          <div class="work-item">
            <figure class="image-container">
              <% url="//www.youtube.com/embed/"+ entrada.link_video.sub(/(http:\/\/|https:\/\/|)(www.youtube.com\/watch\?v=|youtu.be\/)/,'')%>
              <iframe width="300" height="169" src=<%= url%> frameborder="0" allowfullscreen></iframe>
            </figure>
            <h2 class="heading h-02"><%= entrada.nombre %></h2>
            <p class="copy-03"><%= entrada.colegio %></p>
          </div>
          <%end%>
          
          <% end %>
          
           </section>

      </div>

      <div id="work-detail">
        <span class="close-icon">x</span>
        <div class="inner site-inner"></div>
      </div>

    </section>
     <!-- PHOTOGRAPHY -->
    <section id="page-photography" class="section">
      <div class="site-inner">
        <h1 class="heading h-01">Bloopers</h1>

        <section id="photo-grid">
          <% @entradas.each do |entrada| %>
          <% if entrada.link_bloopers.match(/(http:\/\/|https:\/\/|)(www.youtube.com\/watch\?v=|youtu.be\/)/)%>
          <div class="photo-item">
            <figure class="image-container">
              <% url="//www.youtube.com/embed/"+ entrada.link_bloopers.sub(/(http:\/\/|https:\/\/|)(www.youtube.com\/watch\?v=|youtu.be\/)/,'')%>
              <iframe width="300" height="169" src=<%= url%> frameborder="0" allowfullscreen></iframe>
            </figure>
            <h2 class="heading h-02" style="margin: 8px;"><%= entrada.nombre %></h2>
            <p class="copy-03" style="margin: 5px;"><%= entrada.colegio %></p>
          </div>
          <%end%>
          
          <% end %>
          
        </section>
      </div>
    </section>


    <!-- SIGNUP -->
    <section id="page-signup" class="section">
      <div class="site-inner">
        
        <p class="copy-02">Llena el formulario para registrarte.</p>

       <%= render :partial => 'entradas/form' %>

      </div>
    </section>


    <!-- FOOTER -->
    <section id="page-footer">

      


    </section>

  </section>



</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PiensaEnTic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>